name: gen_avr8 install python3 package
on:
  push:
    branches: [ master ]
    paths:
      - 'gen_avr8/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
  pull_request:
    branches: [ master ]
    paths:
      - 'gen_avr8/**'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'setup.py'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
    - name: build and publish
      run: |
        python setup.py --github sdist bdist_wheel
