name: gen_avr8_interface_checker

permissions:
  contents: read

on:
  push:
    branches: [ main ]
    paths:
      - 'gen_avr8/**/*.py'
      - 'setup.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'gen_avr8/**/*.py'
      - 'setup.py'

jobs:
  interface_gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Verify that each concrete class implements a valid interface
        run: |
          python3 gates/gates/interfaces_checker.py gen_avr8
